id: P004197
initial_creation_type: ocr
source_metadata:
  id: bdr:W2CZ7692
  title: སངས་རྒྱས་སེངྒེའི་རྣམ་ཐར་མཐོང་བ་དོན་ལྡན་ངོ་མཚར་ནོར་བུའི་ཕྲེང་བ་ཐར་འདོད་ཡིད་འཕྲོག་བློ་གསལ་མགུལ་རྒྱན་
  author: ''
  volumes:
    418c80bbaf1842709b20186c5433e369:
      image_group_id: I1KG2157
      title: ''
      volume_number: 1
      total_pages: 54
      base_file: v001.txt
