id: opecha:P004197
initial_creation_type: ocr
source_metadata:
  id: bdr:W2CZ7692
  title: སངས་རྒྱས་སེངྒེའི་རྣམ་ཐར་མཐོང་བ་དོན་ལྡན་ངོ་མཚར་ནོར་བུའི་ཕྲེང་བ་ཐར་འདོད་ཡིད་འཕྲོག་བློ་གསལ་མགུལ་རྒྱན་
  volume: ''
  author: ''
