id: I6F2533C1
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T05:01:57+00:00'
last_modified: '2022-06-07T20:59:32.145290+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2CZ7692
  title: སངས་རྒྱས་སེངྒེའི་རྣམ་ཐར་མཐོང་བ་དོན་ལྡན་ངོ་མཚར་ནོར་བུའི་ཕྲེང་བ་ཐར་འདོད་ཡིད་འཕྲོག་བློ་གསལ་མགུལ་རྒྱན་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    9D55:
      image_group_id: I1KG2157
      title: ''
      total_pages: 54
      order: 1
      base_file: 9D55.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
