id: I6F2533C1
legacy_id: P004197
ocr_import_info:
  bdrc_scan_id: W2CZ7692
  source: bdrc
  ocr_info:
    timestamp: '2020-03-23T05:01:34'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T15:16:59.274733+00:00'
last_modified: 2022-09-02 23:17:16.830452
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W2CZ7692
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW2CZ7692
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: སངས་རྒྱས་སེངྒེའི་རྣམ་ཐར་མཐོང་བ་དོན་ལྡན་ངོ་མཚར་ནོར་བུའི་ཕྲེང་བ་ཐར་འདོད་ཡིད་འཕྲོག་བློ་གསལ་མགུལ་རྒྱན།
  author: མཁས་གྲུབ་བྱམས་པ་ཕུན་ཚོགས།
statistics:
  ocr_word_mean_confidence_index: 0.4596532121811098
  ocr_word_median_confidence_index: 0.38999998569488525
quality: null
bases:
  I1KG2157:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG2157
      total_pages: 54
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG2157.txt
    statistics:
      ocr_word_median_confidence_index: 0.38999998569488525
      ocr_word_mean_confidence_index: 0.4596532121811098
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
